# Generated by Django 5.2.5 on 2025-08-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('last_html', models.TextField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('has_changed', models.BooleanField(default=False)),
                ('ignored_lines', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
